- url: https://web-ace.jp/youngaceup/contents/1000121/
  pattern: <span class="updated-date">{}</span>
- url: https://mangacross.jp/api/comics/yabai.json
  pattern: {}
- url: http://to-ti.in/product/mariakodama
  pattern: <time>{}</time>
- url: https://comic-ryu.jp/_oshi/
  pattern: <p class=date>{}</p>
