#!/bin/bash

CACHE_DIR=~/.cache/manga-check
[ -d $CACHE_DIR ] || mkdir -p $CACHE_DIR

usage() {
  cat <<EOM
Usage:
  manga-check init
  manga-check run
EOM
  exit
}

config() {
  cat config.yml |
    sed '/^#/d; s/[ \t]#.*//g' |
    awk '
      function flush() {
        if (url != "" && type != "" && pattern != "") {
          print url
          print type
          print pattern
          print notify_url == "" ? url : notify_url
        }
        url = ""
        notify_url = ""
        type = ""
        pattern = ""
      }
      /^-/ { flush() }
      /^[- ]*url *:/ { url = $0 }
      /^[- ]*notify_url *:/ { notify_url = $0 }
      /^[- ]*html *:/ {
        type = "html"
        pattern = $0
      }
      /^[- ]*json *:/ {
        type = "json"
        pattern = $0
      }
      END { flush() }
    ' |
      sed 's/^[- ]*[a-zA-Z0-9_]* *:  *//g'
}

hashcode() {
  md5sum | grep -o '[0-9a-f]*'
}

extract() {
  URL="$1"
  TYPE="$2"
  PATTERN="$3"
  case "$TYPE" in
    html )
      curl -sL "$URL" | web-grep "$PATTERN"
      ;;
    json )
      curl -sL "$URL" | jq "$PATTERN"
      ;;
  esac
}

init() {
  [ -d $CACHE_DIR ] && rm -r $CACHE_DIR
  mkdir -p $CACHE_DIR
  config |
    while read url; do
      read ty
      read pat
      read notify_url
      F="$CACHE_DIR/$(echo $url | hashcode)"
      extract "$url" "$ty" "$pat" | hashcode > $F
      cat <<EOM
[$(date)] init
Url: $url
Extract Type: $ty
Pattern: $pat
Matched:
---
$(extract "$url" "$ty" "$pat")
---
Cache saved as $F

EOM
    done
}

check() {
  config |
    while read url; do
      read ty
      read pat
      read notify_url
      F="$CACHE_DIR/$(echo $url | hashcode)"
      F_NEW="$CACHE_DIR/$(echo $url | hashcode)-new"
      extract "$url" "$ty" "$pat" | hashcode > $F_NEW
      echo -n "[$(date)] $url ... "
      if diff $F $F_NEW > /dev/null; then
        echo "No Update"
      else
        echo "Updated!!"
        mv $F_NEW $F
        notify "$notify_url"
      fi
    done
}

notify() {
    tw "@ampeloss @unddich @cdddar Check $1 $(date "+%s")"
}

run() {
    while :; do
        wait-at 9:00
        check
        wait-at 12:00
        check
        wait-at 18:00
        check
    done
}

[ $# -eq 0 ] && usage
case "$1" in
  init )
    init
    ;;
  check )
    check
    ;;
  run )
    run
    ;;
  help | --help | -h )
    usage
    ;;
esac
